"pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on

"activate numbers
set nu

nmap <F8> :TagbarToggle<CR>

filetype off                  " required

execute pathogen#infect()

"All of your Plugins must be added before the following line
filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

syntax enable
colorscheme molokai

"To keep airline initialized"
set laststatus=2
set t_Co=256

"au BufNewFile,BufRead *.cpp set syntax=cpp11
autocmd BufNewFile,BufReadPost *.ino,*.pde,*.tpl set filetype=cpp

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

if !exists('g:airline_symbols')
let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

let g:airline_symbols.space = "\ua0"
let g:airline#extensions#tmuxline#enabled = 0
let g:airline_theme='dark'

" re draw
set nolazyredraw

let g:cpp_class_scope_highlight = 1
let g:cpp_experimental_template_highlight = 1

set backspace=indent,eol,start

